var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                      o                          x!!!x          ",
   "                                         xx                      xx!xx          ",
   "                                             o                    xvx           ",
   "                                             x                              xx  ",
   "  x                                       o  x                               x  ",
   "  x                     o                    x                               x  ",
   "  x            xx                            x                             o x  ",
   "  x          xxxxx      o                  x x                               x  ",
   "  x  @      xxxxxxx                   d      x                               x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                  xxxxxxx                                         ",
   "                                                              xxxxx     xxxxx                      o   o   o      ",
   "                                                           xxxxx           xxxxx                                  ",
   "                                                         xxxxxx             xxxxxx                                ",
   "                                                             x     o   o                                          ",
   "                                                             x                                  p   p   p         ",
   "                                                             x   |       |                    xxxxxxxxxxxxxxx!!x  ",
   "                                                             x  !!!x   x!!!                       !!!!!!!!!!!!!x  ",
   "                                                             xxxxxx     xxxxxx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                     x     xx         x   v                       ",
   "                                                                        xxxx        xxx                           ",
   "                                                                  xxxxxxx                       xxx               ",
   "                                                              xxx                              x x                ",
   "                                                 o          x                                 x                   ",
   "                                               xxxxx      x                       xx          x                   ",
   "                                               xx       x                          x         x                    ",
   "                                               x             o  o    xx  xx        xx         x                   ",
   "                              xxx              x     x               x   x         x         x                    ",
   "              xx           x    x              x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx          x      x o            x    xx               x   x   x               x                    ",
   " @           x         x        x              x     x               x   x   x               x                    ",
   " xx  x   xx  x         x        x              x     x               x   xxxxx   xxxxxx      x                    ",
   "             x    o    x       xx o  xx!!!!!!!!x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x    x    x!!!!!xx      xxxxxxxxxxxx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx                      x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxx  xxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                        xxxxxx xxx xxx xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                                           x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                                          xx                                         xxx                      ",
   "  xxx                                     x                                         x!!!x                xxx  ",
   "  x x                xxxxxxxxx            x                                          xxx                 x x  ",
   "  x                          xxx          x                              xxxxx                             x  ",
   "  x                                       x                              x   x                             x  ",
   "  x                                x      x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                                o o    x                              x         xxx                     x  ",
   "  x                           xx | xxx |  x                             xxx       x!!!x          x         x  ",
   "  x             o    o    o   x!!!!xxx!!!!x                             x x        xxx          xxx        x  ",
   "  x                           xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @   s    s    s      x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxx  x xxxxxx x  xxxxxx x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
